Lifters画面情報取得
taku300/FWA pull request #56
Opened 2023-02-04 08:13 UTC by t-ookuma

暇だから作っといた

2023-02-04 16:01 UTC, taku300 requested changes

2023-02-04 16:01 UTC, taku300 commented on app/Http/Controllers/LiftersController.php
$genderに数値を代入するとわかりずらい気がする。
例えば、
Constに"男性" => 1, "女性" => 2 を定義して引っ張り出すなどの改善案が考えられる。

2023-02-04 16:01 UTC, taku300 commented on resources/js/jQuery.js
> +});
jqureyの処理はcommon.jsにまとめてあるのでそちらに追加して欲しい。あと僕が書いたcommom.jsのコメントが正式な形じゃないので書き方jsのコメントの書き方しっとったら教えてほしい。
あと、もしかしてこれはお知らせ・登録編集画面の処理かね？

2023-02-04 16:03 UTC, taku300 requested changes

2023-02-04 16:03 UTC, taku300 commented on resources/js/jQuery.js
> +    // input追加
この処理は!使ってるのでelseでもいい気がする

2023-02-04 16:04 UTC, taku300 requested changes

2023-02-04 16:04 UTC, taku300 commented on app/Libs/DatabaseRegister.php
> +}
これはいつ使う感じ？

2023-02-04 16:05 UTC, t-ookuma commented on app/Http/Controllers/LiftersController.php
/**
 * 男性 = 1
 * 女性 = 2
 */
で対応したい
これだけのためにconst作りたくない

2023-02-04 16:08 UTC, t-ookuma commented on resources/js/jQuery.js
> +});
おけ、テスト用だからローカルで確認してからコード移す。
複数行 → /** */
たぶん？

2023-02-04 16:09 UTC, t-ookuma commented on resources/js/jQuery.js
> +    // input追加
動作見てそれでいけそうなら修正する。
jQueryほとんど使ってないから何が反応してくれるかわからん。

2023-02-04 16:10 UTC, t-ookuma commented on app/Libs/DatabaseRegister.php
> +}
insert, updateの両方に対応できると思う

2023-02-04 16:20 UTC, taku300 commented on app/Http/Controllers/LiftersController.php
なるほどね、了解した。
上記のコメントは飛び出し元に書く感じかな？
提案なんやけどさ。getLiftersList()に数字入れるとコントローラー見た時に分かりずらいかなっていう意図があってコメントした。今後、男性、女性みたいにどのシチュエーションでも使う定数が出てくると思うんよね。やけん、Common Constを作ってそこに、こういった定数を追加していくのがいいと思うんやけどどうかな？
基本的にDBで定義された定数は Constを使って呼び出した方がいい気もする、、

2023-02-05 02:34 UTC, t-ookuma commented on app/Http/Controllers/LiftersController.php
呼び出し先に書く形かな
画面表示するときは使ってもいいと思うけどkeyとして使うときはparamに記載する形にしたい。
余計な処理が走るし、そもそも値が何を示すのかを記載するためのものがparam。

2023-02-05 02:34 UTC, t-ookuma commented on app/Libs/DatabaseRegister.php
> +<?
ここタイポしてんだけど<?phpじゃなくてもいけるようになってる？

2023-02-07 16:03 UTC, t-ookuma commented
お知らせ画面の表示時、createとeditどっち使うの？

2023-02-08 02:57 UTC, taku300 requested changes

2023-02-08 02:57 UTC, taku300 commented on app/Http/Controllers/NewsController.php
>      {
インジェクション使ったものを代入する

2023-02-08 02:57 UTC, taku300 commented on app/Services/NewsLinkService.php
>  }
これは使ってない感じ？

2023-02-08 02:57 UTC, taku300 commented on app/Services/NewsService.php
>  }
処理いい感じ！
あとはServiceとか使ってuse App\Models\News;とかの処理を移した方がいいかもね。
databaseRegisterは引数おおいから名前付き引数とか使うとわかりやすいかもね！
[名前付き引数参考](https://qiita.com/rana_kualu/items/13bc0c30192ee22c1396)

2023-02-08 02:57 UTC, taku300 commented on app/Libs/DatabaseRegister.php
> +}
このstoreAsはトランザクションの対象になるんかね？
対象外やったらデータベース保存失敗してもファイルだけ残るみたいになりそうやけど

2023-02-08 03:02 UTC, t-ookuma commented on app/Services/NewsLinkService.php
>  }
削除対応

2023-02-08 03:05 UTC, t-ookuma commented on app/Services/NewsLinkService.php
>  }
削除対応

2023-02-08 03:05 UTC, t-ookuma commented on app/Services/NewsService.php
>  }
TODO対応

2023-02-15 11:03 UTC, taku300 approved these changes

2023-02-15 11:03 UTC, taku300 commented on app/Services/NewsService.php
> +
$newsDocuments = $this->databaseRegister
ここの部分やけど、ファイルパスだけ綺麗に上書きされるようになるってことかね？

2023-02-15 11:03 UTC, taku300 commented on resources/views/components/layout/head.blade.php
> +</head>
news.jsは多分ここでしか使わんから、newsのブレイドの方のbodyの閉じたぐの前に配置してdefer属性つけた方がいいかも

2023-02-15 11:06 UTC, taku300 requested changes
レビュー完了

2023-02-16 13:10 UTC, merged